version: '3'

services:
  solr:
    build: 
      context: ./solr
      args:
      - http_proxy
      - https_proxy

  indexsvc:
    build:
      context: ./indexsvc
      args:
      - http_proxy
      - https_proxy
    links:
    - solr
    environment:
      no_proxy: 127.0.0.1, localhost, solr
      SOLR_PORT_8983_TCP_ADDR: solr

  blobsvc:
    build:
      context: ./blobsvc
      args:
      - http_proxy
      - https_proxy

  convsvc:
    build:
      context: ./convertsvc
      args:
      - http_proxy
      - https_proxy

  webapp:
    build:
      context: ./webapp
      args:
      - http_proxy
      - https_proxy
    links:
    - indexsvc
    - blobsvc
    environment:
      no_proxy: 127.0.0.1, localhost, blobsvc, indexsvc
      INDEXSVC_PORT_32600_TCP_ADDR: indexsvc
      BLOBSVC_PORT_32500_TCP_ADDR: blobsvc
    ports:
    - 8080:32000

  batchsvc:
    build:
      context: ./batchsvc
      args:
      - http_proxy
      - https_proxy      
    links:
    - indexsvc
    - blobsvc
    - convsvc
    - webapp
    environment:
      no_proxy: 127.0.0.1, localhost, webapp, blobsvc, convsvc, indexsvc
      WEBAPP_PORT_32000_TCP_ADDR: webapp
      CONVSVC_PORT_32400_TCP_ADDR: convsvc
      INDEXSVC_PORT_32600_TCP_ADDR: indexsvc
      BLOBSVC_PORT_32500_TCP_ADDR: blobsvc
